### ISSUE TITLE
Directory does not show path when running into an permission denied error

### ISSUE THREAD

**Issue by Mizzrym** [Simovative/zeus#11]
When class Directory tries to create() a Directory using mkdir() it should use try / catch to add the path to the error message, which helps with debugging a lot. 
Unfortunately php's mkdir doesn't do this by itself, so you'll just see "mkdir: permission denied" and have to search stacktraces for the actual path (which is most often cut off anyways if you're using xdebug at default settings)

**Comment by slider1337** [comment]
Fixed in V2.0.1.
