### ISSUE TITLE
Tests use missleading namespace

### ISSUE THREAD

**Issue by diecktator** [Simovative/zeus#26]
Some tests (e.g. [this one](https://github.com/Simovative/zeus/blob/2633089d40ddb6ef6798918d7c8a67da38c435b6/tests/Integration/TestBundle/Command/TestCommand.php#L2)) use the namespace
`namespace Simovative\Tests\Integration\...` instead of
`namespace Simovative\Zeus\Tests\Integration`

In my eyes the sugested namespace would make clearer, that these are tests for zeus

**Comment by slider1337** [comment]
will be fixed with #40
